server:
    port: 8088

#logging:
#    level:
#        org.springframework: DEBUG

# local H2 DB Setting
spring:
    h2:
        console:
            enabled: true # 콘솔 사용여부
    profiles:
        active: local
    # H2 메모리 DB를 위한 설정
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: none